# Lab | Data Structuring and Combining Data

## Challenge 1: Combining & Cleaning Data

In this challenge, we will be working with the customer data from an insurance company, as we did in the two previous labs. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

But this time, we got new data, which can be found in the following 2 CSV files located at the links below.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Note that you'll need to clean and format the new data.

Observation:
- One option is to first combine the three datasets and then apply the cleaning function to the new combined dataset
- Another option would be to read the clean file you saved in the previous lab, and just clean the two new files and concatenate the three clean datasets

In [21]:
import pandas as pd
import numpy as np

In [22]:
import pandas as pd

def standardize_columns(df):
    df = df.copy()
    df.columns = df.columns.str.strip()

    df = df.rename(columns={
        "ST": "State",
        "GENDER": "Gender"
    })
    return df

df1 = standardize_columns(pd.read_csv("insurance1.csv"))
df2 = standardize_columns(pd.read_csv("insurance2.csv"))
df3 = standardize_columns(pd.read_csv("insurance3.csv"))

combined_insurance_df = pd.concat([df1, df2, df3], ignore_index=True)

In [23]:
import importlib
import cleaning

importlib.reload(cleaning)
insurance_clean_df = cleaning.clean_data(combined_insurance_df)
insurance_clean_df.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,<NA>,Master,NaN,0.0,1000.0,0.0,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59,0.0,94.0,0.0,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17,48767.0,108.0,0.0,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18,0.0,106.0,0.0,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65,36357.0,68.0,0.0,Personal Auto,Four-Door Car,17.269323

In [24]:
insurance_clean_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9137 entries, 0 to 12073
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   9137 non-null   object
 1   state                      9137 non-null   object
 2   gender                     9015 non-null   string
 3   education                  9137 non-null   object
 4   customer_lifetime_value    9130 non-null   float64
 5   income                     9137 non-null   float64
 6   monthly_premium_auto       9137 non-null   float64
 7   number_of_open_complaints  9137 non-null   float64
 8   policy_type                9137 non-null   object
 9   vehicle_class              9137 non-null   object
 10  total_claim_amount         9137 non-null   float64
dtypes: float64(5), object(5), string(1)
memory usage: 856.6+ KB

# Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing data cleaning, formatting, and structuring.

In [25]:
# Your code goes here
marketing_clean_df = pd.read_csv("marketing_customer_analysis_clean.csv")
marketing_clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   unnamed:_0                     10910 non-null  int64
 1   customer                       10910 non-null  object
 2   state                          10910 non-null  object
 3   customer_lifetime_value        10910 non-null  float64
 4   response                       10910 non-null  object
 5   coverage                       10910 non-null  object
 6   education                      10910 non-null  object
 7   effective_to_date              10910 non-null  object
 8   employmentstatus               10910 non-null  object
 9   gender                         10910 non-null  object
 10  income                         10910 non-null  int64
 11  location_code                  10910 non-null  object
 12  marital_status                 10910 non-null  object
 13  monthly_premium_auto           10910 non-null  int64
 14  months_since_last_claim        10910 non-null  float64
 15  months_since_policy_inception  10910 non-null  int64
 16  number_of_open_complaints      10910 non-null  float64
 17  number_of_policies             10910 non-null  int64
 18  policy_type                    10910 non-null  object
 19  policy                         10910 non-null  object
 20  renew_offer_type               10910 non-null  object
 21  sales_channel                  10910 non-null  object
 22  total_claim_amount             10910 non-null  float64
 23  vehicle_class                  10910 non-null  object
 24  vehicle_size                   10910 non-null  object
 25  vehicle_type                   10910 non-null  object
 26  month                          10910 non-null  int64
dtypes: float64(4), int64(6), object(17)
memory usage: 2.2+ MB

In [26]:
marketing_clean_df.head()

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,A,2
1,1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,A,1
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,A,1

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

In [33]:
marketing_pivot = marketing_clean_df.pivot_table(
    values="total_claim_amount",       # the main information we want to display!
    index="sales_channel",    # what becomes the rows
    aggfunc="sum"
)
marketing_pivot=marketing_pivot.round(2)
marketing_pivot

               total_claim_amount
sales_channel
Agent                  1810226.82
Branch                 1301204.00
Call Center             926600.82
Web                     706600.04

Agent brought in the most total revenue, followed by Branch, then Call Center, and Web brought in the least. That means Agent is the strongest channel for revenue generation in this dataset.

2. Create a pivot table that shows the average customer lifetime value per gender and education level. Analyze the resulting table to draw insights.

In [35]:
lifetime_value_pivot = marketing_clean_df.pivot_table(
    values="customer_lifetime_value",       # the main information we want to display!
    index="gender",    # what becomes the rows
    aggfunc="mean", # what we want to do with the values
    columns="education" # what becomes the columns
)
lifetime_value_pivot=lifetime_value_pivot.round(2)
lifetime_value_pivot

education  Bachelor  College   Doctor  High School or Below   Master
gender
F           7874.27  7748.82  7328.51               8675.22  8157.05
M           7703.60  8052.46  7415.33               8149.69  8168.83

Education level seems to affect the values more than gender alone. Females show higher values in Bachelor and High School or Below, while males lead slightly in College, Doctor, and Master. The strongest segment is females with High School or Below, but overall the differences between genders are relatively small.

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

In [36]:
# Your code goes here

bonus_pivot = marketing_clean_df.pivot_table(
    values="number_of_open_complaints",       # the main information we want to display!
    index="month",    # what becomes the rows
    aggfunc="sum", # what we want to do with the values
    columns="policy_type" # what becomes the columns
)
bonus_pivot=bonus_pivot.round(2)
bonus_pivot

policy_type  Corporate Auto  Personal Auto  Special Auto
month
1                    443.43        1727.61         87.07
2                    385.21        1453.68         95.23

In [41]:

long_format = bonus_pivot.stack().reset_index(name="number_of_open_complaints")
long_format

   month     policy_type  number_of_open_complaints
0      1  Corporate Auto                     443.43
1      1   Personal Auto                    1727.61
2      1    Special Auto                      87.07
3      2  Corporate Auto                     385.21
4      2   Personal Auto                    1453.68
5      2    Special Auto                      95.23